---
version: '3.7'
services:
  vpn:
    image: pyunramura/wireguard
    volumes:
      - config:/etc/wireguard
      - ./wg0.conf:/etc/wireguard:ro
      - ./wg_configs:/etc/wireguard:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - LOCAL_NETWORK=192.168.1.0/24,10.0.0.0/16
      - KEEPALIVE=25
      - VPNDNS=8.8.8.8,8.8.4.4
      - WG_USERSPACE=1
      - PEER_PORT=51820
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
