---
name: Dockerfile Update
# From: https://github.com/ludeeus/dockerfile-updater
on:
  workflow_dispatch:
  schedule:
    - cron: '45 2 * * *'
# push:
#   branches: [main]
#   paths:
#     - "**/Dockerfile"
jobs:
  update-dockerfile-deps:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.0

      - name: Update Dockerfile
        uses: ludeeus/dockerfile-updater@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "⚓ chore(deps): update dockerfile deps."
