---
name: Validate Shell Script
# From: https://github.com/reviewdog/action-shellcheck

on:
  pull_request:
    paths:
      - '**/*.sh'
      - 'run'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.head_ref }}
        #   fetch-depth: 0

      - name: Lint Shell Script
        uses: reviewdog/action-shellcheck@v1
        with:
          pattern: "*.sh"
          level: "warning"

      - name: Lint Shell Script
        uses: reviewdog/action-shellcheck@v1
        with:
          pattern: "run"
          level: "warning"
