---
name: Validate Dockerfile
# From: https://github.com/luke142367/Docker-Lint-Action

on:
  pull_request:
    paths:
      - '**/Dockerfile'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.head_ref }}
        #   fetch-depth: 0

      - name: Lint Dockerfile
        uses: luke142367/Docker-Lint-Action@v1.0.0
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
