---
name: Validate Dockerfile
# From: https://github.com/luke142367/Docker-Lint-Action

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/Dockerfile'
jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Lint Dockerfile
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [validate]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false

      - name: Build arm64v8
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: false

      - name: Build arm32v7
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v7
          push: false
