---
name: Lint Markdown files
# From: https://github.com/tomwhross/write-good-action

on:
  push:
    paths:
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.md'
    branches:
      - main

jobs:
  write_good_job:
    runs-on: ubuntu-latest
    name: A job to lint Markdown files
    steps:
    - uses: actions/checkout@v2

    - name: write-good action step
      id: write-good
      uses: tomwhross/write-good-action@v1.2

    - name: Get the write-good output
      run: echo "${{ steps.write-good.outputs.result }}"

    - name: Post comment
      uses: mshick/add-pr-comment@v1
      if: ${{ steps.write-good.outputs.result }}
      with:
        message: |
          ${{ steps.write-good.outputs.result }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default